services:
  postgres:
    image: postgres:17-alpine
    container_name: pg_sales_management_ctn
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - '${POSTGRES_PORT}:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - sales_management_ntk

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_sales_management_ctn
    ports:
      - '${PGADMIN_PORT}:80'
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PASSWORD}
    depends_on:
      - postgres
    networks:
      - sales_management_ntk

volumes:
  postgres_data:

networks:
  sales_management_ntk:
    driver: bridge
